---
title: 'Stage 2: Draft Exploratory Analysis'
author: "Ellie Hall and Conner Harwood"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Topic and Motivation

We are looking at how water usage and water-related land use changes in Utah counties lying within the Great Salt Lake Basin have contributed to variations in Great Salt Lake (GSL) water levels. We'll also be using predictive analysis to look at potential future changes to GSL levels using water use trends, changes in water-related land use, and precipitation and population trends. The specific counties we're focusing on, which lie fully or mostly within the GSL Basin, are Box Elder, Cache, Davis, Morgan, Rich, Salt Lake, Tooele, Utah, and Weber.

Utah has been the [fastest growing state since 2010](https://worldpopulationreview.com/state-rankings/fastest-growing-states), and much of this growth comes in counties closely connected to the Great Salt Lake. The GSL has also been facing dangerously low and decreasing water levels over the past several decades. If this trend continues, the economic, environmental, and ecological consequences to the region would be drastic. Declining lake levels expose lakebed that contains dangerous heavy metals such as lead, mercury, and arsenic. As the exposed lakebed dries up, winds kick up dust storms that pose significant health risks to the surrounding communities. Lower lake levels also negatively impact the biology and wildlife that are dependent on a healthy lake, including brine shrimp and millions of migratory birds. Economic sectors cloesly tied to the GSL, including recreation and industry, are also negatively affected by declining levels. Thus, it's important to understand how water use in the Great Salt Lake Basin faced with population pressures and a changing climate will impact the health and future of the Great Salt Lake and its surrounding communities. 

Furthermore, agriculture is the largest water user in the state of Utah, using 68% of the state's water supply, yet only generates 0.2% of Utah's GDP [source](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjU4_Tf8aOCAxU9MjQIHS19CYEQFnoECA4QAw&url=https%3A%2F%2Fcontent.csbs.utah.edu%2F~lozada%2FResearch%2FUtahAgWaterUseHay.docx%23%3A~%3Atext%3DUsing%252068%2525%2520of%2520Utah%27s%2520water%2Cto%2520which%2520we%2520will%2520return.&usg=AOvVaw0IdpqkRNtyRjWG_ycnpIPq&opi=89978449). Thus, it’s important to understand water use and land trends in this sector to enact policies that curb their impacts on the Great Salt Lake.


# Data Descriptions

**Water Use**
Obtained through the Utah Division of Water Rights [here](https://waterrights.utah.gov/asp_apps/generalWaterUse/WaterUseList.asp), this data includes all water rights holders in Utah dating back to 1959. Utah has surprisingly complete water use data that is publicly available. It has records on total monthly water usage in gallons for each water user, and breaks down this usage by type of use (e.g. agricultural, commercial, water supplier), as well as several other variables of interest. It also has latitude and longitude information for most water users, which we may use at some point in the project for spatial analysis. We're looking at data on water usage in the 9 GSL Basin counties. The data does not indicate whether water usage records are *consumptive* uses, which have much larger impacts on the Great Salt Lake than non-consumptive uses, as this water is not returned to the watershed basin. Though this is a limitation of the data, we'll still be able to gain a solid understanding of water usage impacts on the Great Salt Lake.

**Great Salt Lake Elevation Levels**
Obtained through the USGS using the `dataRetrieval` package in R, we've gathered daily water level observations dating back to 1966. The two relevant gauges are the Saltair Boat Harbor gauge in the South arm of the lake, and the gauge near Saline, UT in the North arm (the lake was essentially split into two by a railroad causeway in the 1950s). Though the water levels of the two arms are typically very similar, we've used the average of the two gauge values for our observations. The gauges measure surface level elevation above sea level in feet.

**Water-Related Land Use**
Obtained through the Utah Division of Water Resources [here](https://dwre-utahdnr.opendata.arcgis.com/pages/wrlu-data), this data includes yearly composition of water-related land use by county and by basin. Each observation in a given year contains the acreage of a specific plot of land area as well as a description of the type of water use on that land (e.g. crop type, urban use, pasture).

**County Resident Populations**
Obtained through Federal Reserve Economic Data (FRED) [here](https://fred.stlouisfed.org/categories/30154), it has yearly resident population numbers for each Utah county dating back to 1970.

**Precipitation Data**
Obtained through NOAA [here](https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/county/time-series/UT-057/pcp/all/1/1959-2023), it has monthly total precipitation records in each of the 9 counties for each year dating back to 1959. 

**Streamflows Data**
We used the `dataRetrieval` package to download data on daily streamflows at the start and end of the Weber and Bear Rivers, which flow into the Great Salt Lake. Another major inflow to the GSL is the Jordan River, but streamflow data for the start of this river does not exist. However, we decided that won't be using this data in our analysis, though we open to feedback of ways we might be able to make use of it.


# Data Processing

**Water Use**
The water use .csv files for each of the 9 counties included two data tables containing different variables and information on entities with water user rights. One of the tables contained the monthly water usage data we're interested, and the other table had county information which we merged with the first table after cleaning them both. The main cleaning needed with this data was selecting and renaming the relevant variables, addressing NA and 0 values, and merging into one dataset with the population data. The data was also converted from wide to long format by monthly water use. Observations missing year, as well as those containing no water usage values, were removed. Some of the latitude/longitude entries were 0, which we converted to NA.

Some observations had a non-zero value for total usage in a year, but their monthly values were all 0. Looking at the original database on the Utah Division of Water Rights website, the total usage numbers seemed to be correct, and the 0s for the monthly data was simply a lack of records. This occurred mostly in earlier years. Since we wanted to look at monthly water usage, not just yearly, we imputed weighted averages of these months. The weights were determined by the percent of the total water usage in the entire dataset that each month's total made up. There may be ways to get a better estimate of these monthly averages, perhaps by using weights of monthly usage within a given year, but we did not feel the extra effort would be beneficial enough. The are some observations with high usage in a specific month, and 0s for the other months, but since this aligned with the original data records (and likely implies zero water usage for that month), we did not impute for these observations.

Two observations were removed that had water usage magnitudes higher than the rest of the dataset, and since the original database did not show values this high, we felt it safe to remove them entirely.

**Great Salt Lake Elevation Levels**
For the GSL levels data, we first cleaned the North Arm and South Arm datasets separately. Not much cleaning was necessary, we primarily selected and renamed relevant variables, then collapsed the daily water level values into monthly means for each year. The North and South Arms were then merged into one dataset, and the average levels between the two gauges was calculated to give us the main water level values we're interested in.

**Water-Related Land Use**
The water-related land use data started out as separate datasets for difference time periods, and most had slightly different variables. We selected the relevant variables from each to have consistent columns across the datasets, which were then appended into one land use dataset. We then went through the cleaning steps and selected the 9 Utah counties of interest.

**County Resident Populations**
We downloaded this data from FRED for our specific counties of interest, and it came in an already mostly clean .xls file. All that was needed for further cleaning was reading the file into RStudio, converting to long format, extracting year from the date column, and changing some variables names. This data was then merged with the water use data by county and year. Populations were expressed in thousands of people, which we converted by multiplying by 1000 to express it as its actual number.

**Precipitation Data**
The precipitation data was downloaded separately for each county, from which we then cleaned the date values and added a county variable for each county. That data was then appended into one dataset, and we did a few checks of the data before finalizing it. Overall not much cleaning was needed here.

**Master Dataset**
To start merging the data into one master dataset, we started with the water use and GSL levels data, and merged these by year and month, since we wanted the average GSL level value for a given year and month. This dataset was then merged with the precipitation data by year, month, and county. To get all the data on the same time scale, we filtered all observations before 1966, since the Great Lake levels data constrains us to this.

We did not merge the land use data with the master dataset. This data is only at the yearly, not monthly, level, and since for much of our analysis we wanted to look at monthly changes, we kept it separate. We may still end up using this data for the econometric analysis (though we are still undecided exactly how we might use it), and did perform some exploratory analysis with it.


# Exploratory Analysis